import type { FAQItem } from '@/app/_components/seo/StaticFAQPanel';

// Meta / methodology only — never include concrete numbers, percentages or
// dates that go stale. Live figures belong in the SSR'd page content.

export const METHODOLOGY_FAQ: FAQItem[] = [
  {
    q: 'Where does the temperature data on this site come from?',
    aText:
      'Country-level temperatures: Berkeley Earth and the Copernicus Climate Change Service ' +
      '(C3S / ERA5). Global mean surface temperature: NOAA NCEI, NASA GISS and Hadley Centre ' +
      '(HadCRUT5). US state temperatures: NOAA NCEI nClimDiv. UK temperatures: Met Office HadUK-Grid.',
  },
  {
    q: 'How is the climate baseline calculated?',
    aText:
      'Anomalies are calculated against the 1991–2020 climate normal where available, in line with ' +
      'WMO standard practice. NOAA datasets that natively use a 1901–2000 baseline are re-baselined ' +
      'to 1991–2020 (or 1961–1990 for cross-region rankings) so different sources can be compared on ' +
      'equal terms. Pre-industrial comparisons (1850–1900) are used for global mean temperature where ' +
      'the source data supports it. The exact baseline is shown on each chart.',
  },
  {
    q: 'How often is the data updated?',
    aText:
      'Most underlying datasets refresh on a monthly cadence, and the site is rebuilt on the same ' +
      'cadence — typically within days of the previous month\'s figures being released. Live ' +
      'indicators (CO₂, methane, sea ice, ENSO state) refresh more frequently from their source APIs.',
  },
  {
    q: 'How are countries and regions ranked?',
    aText:
      'The /climate/rankings page sorts every supported country, US state, UK nation and UK region ' +
      'by their 1-month, 3-month or 12-month temperature anomaly versus the 1961–1990 baseline ' +
      '(chosen for cross-region comparison). Tie-breaks use the longer time horizon.',
  },
  {
    q: 'How are AI-written summaries generated?',
    aText:
      'Per-region narrative summaries are generated by Google Gemini 2.5 Flash, with the live data ' +
      'snapshot for that region passed in as structured context and Google Search grounding enabled ' +
      'so the model can cite recent reporting. Generated text is cached for the month and refreshes ' +
      'with each new data release. The grounding sources are listed alongside each summary.',
  },
];
